import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Sign in to Nirvista': 'Sign in to Nirvista',
      'Send, spend and save smarter': 'Send, spend and save smarter',
      'Sign In with Google': 'Sign In with Google',
      'Sign In with Apple': 'Sign In with Apple',
      'Or with email': 'Or with email',
      'Username or email': 'Username or email',
      'Password': 'Password',
      'Send': 'Send',
      'GetHelp': 'GetHelp',
      'Analytics': 'Analytics',
      'Recipients': 'Recipients',
      'Transactions': 'Transactions',
      'Reason': 'Reason',
      'ForgetPassword': 'ForgetPassword',
      'Authentication': 'Authentication',
      'Sell Crypto': 'Sell Token',
      'BankDeposit': 'BankDeposit',
      'Dashboard': 'Dashboard',
      'Credit Card': 'Credit Card',
      'Messages': 'Messages',
      'My Wallets': 'My Wallets',
      'Buy': 'Buy',
      'Sell': 'Sell',
      'I have :': 'I have :',
      'More': 'More',
      'Transfer': 'Transfer',
      'Important account details': 'Important account details',
      'Receive': 'Receive',
      'Transaction': 'Transaction',
      'Currency': 'Currency',
      'Quick Exchage': 'Quick Exchage',
      'Unlimited Cashback': 'Unlimited Cashback',
      'Instant 2% back on all your spend to your account': 'Instant 2% back on all your spend to your account',
      'Log out': 'Log out',
      'Account settings': 'Account settings',
      'Your details': 'Your details',
      'Remember me': 'Remember me',
      'Forgot Password?': 'Forgot Password?',
      'Sing In': 'Sing In',
      'Don’t have an account?': 'Don’t have an account?',
      'Sign Up': 'Sign Up',
      'Sign In': 'Sign In',
      'Privacy Policy': 'Privacy Policy',
      'Copyright 2023': 'Copyright 2023',
      'Speady, Easy and Fast': 'Speady, Easy and Fast',
      'Nirvista helps you set saving goals, earn cashback rewards, and get paychecks up to two days early. Get a \$20 bonus when you receive qualifying direct deposits.': 'Nirvista helps you set saving goals, earn cashback rewards, and get paychecks up to two days early. Get a \$20 bonus when you receive qualifying direct deposits.',
      'Sign up for an account': 'Sign up for an account',
      'Already have an account?': 'Already have an account?',
      'First name': 'First name',
      'Last name': 'Last name',
      'Massa, vel donec tempor at quisque eget sapien. Ut sit orc': 'Massa, vel donec tempor at quisque eget sapien. Ut sit orc',
      'Biffco Enterprises': 'Biffco Enterprises',
      'Deposit Cryptocurrency': 'Deposit Cryptocurrency',
      '18 hour ago': '18 hour ago',
      'from': 'from',
      'Alesia Alexandra': 'Alesia Alexandra',
      'Received a new payment ': 'Received a new payment ',
      'Payment Received': 'Payment Received',
      'You have sent a new Transaction of ': 'You have sent a new Transaction of ',
      'Email': 'Email',
      'Decline': 'Decline',
      'Pay Now': 'Pay Now',
      '1 hour ago': '1 hour ago',
      '5 mins ago': '5 mins ago',
      'You have a new payment request from ': 'You have a new payment request from ',
      'New Transaction Sent': 'New Transaction Sent',
      'to ': 'to ',
      'Cindy Lillibridge': 'Cindy Lillibridge',
      '2 mins ago ': '2 mins ago',
      'You have sent ': 'You have sent ',
      'Tenner Stafford': 'Tenner Stafford',
      'Mark all as read': 'Mark all as read',
      'Notifications': 'Notifications',
      'Activity': 'Activity',
      'Settings': 'Settings',
      'Get Help': 'Get Help',
      'Income': 'Income',
      'Wallet': 'Wallet',
      'Recent Transactions': 'Recent Transactions',
      'Jan 10 - Jan 16': 'Jan 10 - Jan 16',
      'Expenses': 'Expenses',
      'View all': 'View all',
      'Money Flow': 'Money Flow',
      'See all notifications': 'See all notifications',
      'Yesterday': 'Yesterday',
      'By creating an account, you agreeing to our': 'By creating an account, you agreeing to our',
      'and': 'and',
      'Electronics Communication Policy.': 'Electronics Communication Policy.',
      'Verify your email': 'Verify your email',
      'We have sent code to your email ': 'We have sent code to your email ',
      'alesiaka******@mail.com': 'alesiaka******@mail.com',
      'Resend code in ': 'Resend code in ',
      'Money Flow ': 'Money Flow',
      'Send Link ': 'Send Link',
      'Upgrade Now': 'Upgrade Now',
      'Spend whiletravelling ': 'Spend whiletravelling',
      'Send money worldwide': 'Send money worldwide',
      'Gain exposure to financial assets': 'Gain exposure to financial assets',
      'Spend or save daily ': 'Spend or save daily',
      'Need help with your account?': 'Need help with your account?',
      'Tell us your main reason for using Nirvista?': 'Tell us your main reason for using Nirvista?',
      'Tell us about the current situation and we will make the right recommendations for you': 'Tell us about the current situation and we will make the right recommendations for you',
      'Enter the email address associated with your account and we will send you a link to reset your password.': 'Enter the email address associated with your account and we will send you a link to reset your password.',
"MyWallets":"MyWallets",
"CreditCard":"CreditCard",
"SellCrypto":"SellCrypto",
"SignIn":"SignIn",
"Signup":"Signup",
      "Buy Crypto":"ICO Coin",
"Auth Pages":"Auth Pages",
    },
    'ur_PK': {
      'Transaction': 'الفواتير',
      'Dashboard': 'لوحة القيادة',
      'Messages' : "رسائل",
      'My Wallets': "محافظ",
      'Transfer' : "تحويل" ,
      'CreditCard' : "بطاقات الائتمان",
      'BankDeposit' : "وديعة بنكية",
      'Sell Crypto':"Sell Token",
      'SignIn':"تسجيل الدخول",
      'Signup':"اشتراك",
      'Authentication':"المصادقة",
      'ForgetPassword': "نسيت كلمة المرور",
      'Reason':"سبب",
      'Transactions':"المعاملات",
      'Recipients':"المستلمون",
      'Analytics':"تحليلات",
      'Get Help':"احصل على مساعدة",
      'Settings':"إعدادات",
      'Buy Crypto':"ICO Coin",
      'Auth Pages':"صفحات المؤلف",
      'Activity':"نشاط",
    }
  };
}
